name: sipcot
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.11.0
  http: ^1.3.0
  geojson: ^1.0.0
  provider: ^6.1.2
  turf: ^0.0.10
  logger: ^2.5.0
  get: ^4.7.2
  shared_preferences: ^2.5.2
  video_player: ^2.9.3
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  image_gallery_saver: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/localJSON/map_style.json
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
